name: Test Job  

on:  
  workflow_dispatch:  
    inputs:  
      environment:  
        description: 'Which environment to deploy to'  
        required: true  
        default: 'production'  
      deploy_version:  
        description: 'Version to deploy'  
        required: false  
  
jobs:  
  deploy:  
    runs-on: ubuntu-latest  
      
    steps:  
    - name: Checkout repository  
      uses: actions/checkout@v2  
  
    - name: Print inputs  
      run: |  
        echo "Deploying to environment: ${{ github.event.inputs.environment }}"  
        echo "Deploying version: ${{ github.event.inputs.deploy_version }}"
        pwd
        ls
        python test.py
